apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.general.deployNamespace }}
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
