apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.general.deployNamespace }}
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000