apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  namespace: {{ .Values.general.deployNamespace }}
spec:
  selector:
    app.kubernetes.io/name: postgres-master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432