apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kaas
data:
  grafana_username: "username"
  grafana_password: "password"
  prometheus-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.kaas.svc.cluster.local:9090
        basicAuth: false
        isDefault: true
        editable: true