apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kaas
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api'
        static_configs:
          - targets: ['api.kaas.svc.cluster.local:8081']