apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.general.deployNamespace }}
data:
  grafana_username: {{ .Values.grafana.username }}
  grafana_password: {{ .Values.grafana.password }}
  prometheus-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.grafana.prometheusUrl }}
        basicAuth: false
        isDefault: true
        editable: true
