apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.general.deployNamespace }}
type: Opaque
data:
  postgres_password: {{ .Values.postgres.password | b64enc }}
  postgres_rep_password: {{ .Values.postgres.replicationPassword | b64enc }}
