
general:
  deployNamespace: kaas
  releaseName: kaas-api
  releaseNamespace: kaas

image:
  api:
    url: kaas-api
    tag: "0.1.0"
    pullPolicy: Never
  grafana:
    url: grafana/grafana
    tag: "10.4.3"
    pullPolicy: Never
  prometheus:
    url: prom/prometheus
    tag: "v2.52.0"
    pullPolicy: Never
  postgres:
    url: bitnami/postgresql
    tag: latest
    pullPolicy: Never
  inspector:
    url: inspector
    tag: "0.1.0"
    pullPolicy: Never

replicas:
  api: 2
  grafana: 1
  prometheus: 1
  masterPostgres: 1
  slavePostgres: 1
  inspector: 1

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

api:
  listenAddress: "0.0.0.0:8081"

grafana:
  username: "admin"
  password: "password"
  prometheusUrl: "http://prometheus.kaas.svc.cluster.local:9090"

postgres:
  dbName: "kaas"
  slaveHost: "postgres-slave.kaas.svc.cluster.local"
  masterHost: "postgres-master.kaas.svc.cluster.local"
  username: "username"
  password: "password"
  replicationUsername: "username-rep"
  replicationPassword: "password"

prometheus:
  scrapeInterval: "5s"
  targetEndpoint: "api.kaas.svc.cluster.local:8081"

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80
  memoryUtilization: 80

inspector:
  targetNamespace: "default"

ingress:
  host:
    api: kaas.local
    prometheus: prometheus.local
    grafana: grafana.local