apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: kaas
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
      - name: api
        image: kaas-api:0.1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8081
        env:
        - name: LISTEN_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: listen_address
        - name: PQ_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_port
        - name: PQ_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_slave_host
        - name: PQ_DBNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_dbname
        - name: PQ_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_username
        - name: PQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  postgres-secret
              key: postgres_password
        startupProbe:
          exec:
            command:
              - cat
              - /tmp/startup-complete
          initialDelaySeconds: 80
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 100
          periodSeconds: 10
          failureThreshold: 5