apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: kaas
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.4.3
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              name: grafana-config
              key: grafana_username
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: grafana-config
              key: grafana_password
        volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana/provisioning/datasources/prometheus-datasource.yml
          subPath: prometheus-datasource.yml
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config