apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: kaas
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"